services:
  next-app:
    container_name: next-app
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    command: yarn run dev
    # Set environment variables based on the .env file
    env_file:
      - .env    
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: server
    image: "fm-dinamic-api:${TAG}"
    command: go run ./main.go
    build:
      context: ./server
      dockerfile: server.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./server
    environment:
      - DB_URL='host=${POSTGRES_HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=${POSTGRES_PORT} sslmode=disable TimeZone=Asia/Shanghai'
      - PORT=8080
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db

  db: 
    container_name: db
    image: postgres:16-alpine
    # restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_fm:/var/lib/postgresql/data

volumes:
  postgres_fm: {}

networks:
  fm-network:
    name: fm-network
    external: true