import type { Metadata } from "next";
import { fonts } from "@/app/fonts";
import { Provider } from "@/app/provider";
import "../globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | FM Dinamic",
    default: "FM Dinamic",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.poppins.variable}>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
